ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.0.277"
    hooks:
      - id: ruff
        args: ["--fix",--ignore=E741, --exclude=__init__.py]
